project:
  type: website

website:
  title: "CSGO Weapon Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Models.qmd
        text: Models
      - href: sources.qmd
        text: Sources
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



